version: '3'

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Asia/Calcutta
#      - PLEX_CLAIM=claim-xxxx
    volumes:
      - ./var/lib/plexmediaserver:/config
      - /mnt/cloud:/mnt/cloud
    devices:
      - /dev/dri:/dev/dri  # Pass Intel GPU device for transcoding
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  default:
    external:
      name: swag_default
